version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  # @see https://github.com/cypress-io/circleci-orb
  # cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

#      - run:
#          name: Run eslint
#          command: yarn lint

      - run:
          name: JUnit
          command: yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: reports

      - run:
          name: Run build
          command: yarn build

#      - slack/status:
#          fail_only: true
#          # mentions: "here"
#          # only_for_branches: 'master'

# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           cache-key: cache-{{ .Branch }}-{{ checksum "package.json" }}
#           yarn: true
#           store_artifacts: true
#           start: 'yarn run dev'
#           wait-on: 'http://localhost:3000'
# 起動させると Error occurred while trying to proxy request になる｡
# circleciからAPIにアクセスできないため